-- ============================================================
-- RLS POLICY REFERENCE
-- ============================================================
-- public.user_role() is defined in schema.sql
-- Lives in public schema (Supabase protects auth schema from custom functions)
-- Use these patterns when creating RLS policies:
--
-- Standard access (any staff):
--   USING (public.user_role() IN ('admin', 'manager'))
--
-- Sensitive (senior only):
--   USING (public.user_role() IN ('admin', 'senior_manager'))
--
-- Admin only (mental health, addiction):
--   USING (public.user_role() = 'admin')
--
-- Manager sees own projects only:
--   USING (public.user_role() = 'admin' OR manager_id = auth.uid())
--
-- Client sees own projects (future):
--   USING (public.user_role() = 'client'
--     AND client_id IN (SELECT id FROM clients WHERE user_id = auth.uid()))
--
-- Member sees own data (future):
--   USING (public.user_role() = 'member'
--     AND member_id = (SELECT id FROM members WHERE user_id = auth.uid()))

